### ISSUE TITLE
[Suggestion] Same Behavior With Campfires' Unlit State

### ISSUE THREAD

**Issue by RyanCR03** [realguyman/totally_lit#1]
Same Behavior from torch with the unlit state of campfires.

**Comment by realguyman** [comment]
I've been working on torches (mostly complete, I think) and lanterns. I will be trying to implement the same feature for campfires.

Campfires will be a different story, because internally it is already a tickable block entity. I won't be able to use the same approach as the torches and lanterns because of how the code is internally for campfires.

Still trying to decide on how to approach campfires, and the same can be said for candles.

**Comment by realguyman** [comment]
I finished a working implementation of modifying the campfire's default state to have `LIT` as `false`. However, I still need to find a solution for having a set amount of time they'll last for.

**Comment by realguyman** [comment]
@RyanCR03 There's a mostly working implementation now, I just need to do more testing. With NBT I'm able to track how long the campfire has been burning for. Coming soon at 0.6.0. :)

**Comment by realguyman** [comment]
With the [release of 0.6.0](https://www.curseforge.com/minecraft/mc-mods/totally-lit/files/3662580) which introduced campfire functionality, this issue should no longer be open.
